jQuery(document).ready ($) ->
  $('.click_menu_container').click ->
    $('.selected').removeClass 'selected'
    $(this).addClass 'selected'
    return
  $('.selected_pag').click ->
    $('.current').removeClass 'current'
    $(this).addClass 'current'
    return
  (($) ->
    $ ->
      $('#nav li').hover (->
        $(this).find('ul:first').css(display: 'none').slideDown 400
        return
      ), ->
        $(this).find('ul:first').fadeOut 'slow'
        return
      return
    return
  ) jQuery
  return

# ---
# generated by js2coffee 2.1.0